// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: bookingservice/v1/booking.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------- Messages ----------------
type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,4,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TotalCost     float32                `protobuf:"fixed32,7,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Booking) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Booking) GetTotalCost() float32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,3,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateBookingRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type CreateBookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingReply) Reset() {
	*x = CreateBookingReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingReply) ProtoMessage() {}

func (x *CreateBookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingReply.ProtoReflect.Descriptor instead.
func (*CreateBookingReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookingReply) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{4}
}

type ListBookingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsReply) Reset() {
	*x = ListBookingsReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsReply) ProtoMessage() {}

func (x *ListBookingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsReply.ProtoReflect.Descriptor instead.
func (*ListBookingsReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ListBookingsReply) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBookingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConfirmBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmBookingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConfirmBookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingReply) Reset() {
	*x = ConfirmBookingReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingReply) ProtoMessage() {}

func (x *ConfirmBookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingReply.ProtoReflect.Descriptor instead.
func (*ConfirmBookingReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmBookingReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBookingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateBookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingReply) Reset() {
	*x = UpdateBookingReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingReply) ProtoMessage() {}

func (x *UpdateBookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingReply.ProtoReflect.Descriptor instead.
func (*UpdateBookingReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBookingReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLockedSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockedSeatsRequest) Reset() {
	*x = GetLockedSeatsRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockedSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockedSeatsRequest) ProtoMessage() {}

func (x *GetLockedSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockedSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetLockedSeatsRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{11}
}

func (x *GetLockedSeatsRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetLockedSeatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []string               `protobuf:"bytes,1,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockedSeatsReply) Reset() {
	*x = GetLockedSeatsReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockedSeatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockedSeatsReply) ProtoMessage() {}

func (x *GetLockedSeatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockedSeatsReply.ProtoReflect.Descriptor instead.
func (*GetLockedSeatsReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{12}
}

func (x *GetLockedSeatsReply) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type LockSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatRequest) Reset() {
	*x = LockSeatRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatRequest) ProtoMessage() {}

func (x *LockSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatRequest.ProtoReflect.Descriptor instead.
func (*LockSeatRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{13}
}

func (x *LockSeatRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *LockSeatRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *LockSeatRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LockSeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatReply) Reset() {
	*x = LockSeatReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatReply) ProtoMessage() {}

func (x *LockSeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatReply.ProtoReflect.Descriptor instead.
func (*LockSeatReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{14}
}

func (x *LockSeatReply) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type UnlockSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockSeatRequest) Reset() {
	*x = UnlockSeatRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockSeatRequest) ProtoMessage() {}

func (x *UnlockSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockSeatRequest.ProtoReflect.Descriptor instead.
func (*UnlockSeatRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{15}
}

func (x *UnlockSeatRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UnlockSeatRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *UnlockSeatRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlockSeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockSeatReply) Reset() {
	*x = UnlockSeatReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockSeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockSeatReply) ProtoMessage() {}

func (x *UnlockSeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockSeatReply.ProtoReflect.Descriptor instead.
func (*UnlockSeatReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{16}
}

func (x *UnlockSeatReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBookedSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookedSeatsRequest) Reset() {
	*x = GetBookedSeatsRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookedSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookedSeatsRequest) ProtoMessage() {}

func (x *GetBookedSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookedSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetBookedSeatsRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{17}
}

func (x *GetBookedSeatsRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetBookedSeatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatIds       []string               `protobuf:"bytes,1,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookedSeatsReply) Reset() {
	*x = GetBookedSeatsReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookedSeatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookedSeatsReply) ProtoMessage() {}

func (x *GetBookedSeatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookedSeatsReply.ProtoReflect.Descriptor instead.
func (*GetBookedSeatsReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{18}
}

func (x *GetBookedSeatsReply) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

// Event messages
type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{19}
}

func (x *GetEventRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	TotalSeats    uint32                 `protobuf:"varint,4,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	PricePerSeat  uint32                 `protobuf:"varint,5,opt,name=price_per_seat,json=pricePerSeat,proto3" json:"price_per_seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventReply) Reset() {
	*x = GetEventReply{}
	mi := &file_bookingservice_v1_booking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventReply) ProtoMessage() {}

func (x *GetEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_bookingservice_v1_booking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventReply.ProtoReflect.Descriptor instead.
func (*GetEventReply) Descriptor() ([]byte, []int) {
	return file_bookingservice_v1_booking_proto_rawDescGZIP(), []int{20}
}

func (x *GetEventReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEventReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetEventReply) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetEventReply) GetTotalSeats() uint32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *GetEventReply) GetPricePerSeat() uint32 {
	if x != nil {
		return x.PricePerSeat
	}
	return 0
}

var File_bookingservice_v1_booking_proto protoreflect.FileDescriptor

const file_bookingservice_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x1fbookingservice/v1/booking.proto\x12\n" +
	"booking.v1\x1a\x1cgoogle/api/annotations.proto\"\xbe\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x04R\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x19\n" +
	"\bseat_ids\x18\x04 \x03(\tR\aseatIds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"total_cost\x18\a \x01(\x02R\ttotalCost\"e\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x04R\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x03 \x03(\tR\aseatIds\"C\n" +
	"\x12CreateBookingReply\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.booking.v1.BookingR\abooking\"#\n" +
	"\x11GetBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x15\n" +
	"\x13ListBookingsRequest\"D\n" +
	"\x11ListBookingsReply\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.booking.v1.BookingR\bbookings\"&\n" +
	"\x14CancelBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"'\n" +
	"\x15ConfirmBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"-\n" +
	"\x13ConfirmBookingReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\">\n" +
	"\x14UpdateBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\".\n" +
	"\x12UpdateBookingReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x15GetLockedSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\"0\n" +
	"\x13GetLockedSeatsReply\x12\x19\n" +
	"\bseat_ids\x18\x01 \x03(\tR\aseatIds\"`\n" +
	"\x0fLockSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\"'\n" +
	"\rLockSeatReply\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked\"b\n" +
	"\x11UnlockSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\"+\n" +
	"\x0fUnlockSeatReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x15GetBookedSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\"0\n" +
	"\x13GetBookedSeatsReply\x12\x19\n" +
	"\bseat_ids\x18\x01 \x03(\tR\aseatIds\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x90\x01\n" +
	"\rGetEventReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1f\n" +
	"\vtotal_seats\x18\x04 \x01(\rR\n" +
	"totalSeats\x12$\n" +
	"\x0eprice_per_seat\x18\x05 \x01(\rR\fpricePerSeat2\xea\t\n" +
	"\x0eBookingService\x12j\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a\x1e.booking.v1.CreateBookingReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/bookings\x12f\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x1e.booking.v1.CreateBookingReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/bookings/{id}\x12d\n" +
	"\fListBookings\x12\x1f.booking.v1.ListBookingsRequest\x1a\x1d.booking.v1.ListBookingsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/bookings\x12o\n" +
	"\rUpdateBooking\x12 .booking.v1.UpdateBookingRequest\x1a\x1e.booking.v1.UpdateBookingReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/v1/bookings/{id}\x12o\n" +
	"\rCancelBooking\x12 .booking.v1.CancelBookingRequest\x1a\x1e.booking.v1.CreateBookingReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/bookings/{id}\x12y\n" +
	"\x0eConfirmBooking\x12!.booking.v1.ConfirmBookingRequest\x1a\x1e.booking.v1.CreateBookingReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1/bookings/{id}/confirm\x12}\n" +
	"\x0eGetBookedSeats\x12!.booking.v1.GetBookedSeatsRequest\x1a\x1f.booking.v1.GetBookedSeatsReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/events/{event_id}/booked-seats\x12}\n" +
	"\x0eGetLockedSeats\x12!.booking.v1.GetLockedSeatsRequest\x1a\x1f.booking.v1.GetLockedSeatsReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/events/{event_id}/locked-seats\x12n\n" +
	"\bLockSeat\x12\x1b.booking.v1.LockSeatRequest\x1a\x19.booking.v1.LockSeatReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/events/{event_id}/lock-seat\x12v\n" +
	"\n" +
	"UnlockSeat\x12\x1d.booking.v1.UnlockSeatRequest\x1a\x1b.booking.v1.UnlockSeatReply\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/events/{event_id}/unlock-seat\x12[\n" +
	"\bGetEvent\x12\x1b.booking.v1.GetEventRequest\x1a\x19.booking.v1.GetEventReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/events/{id}B)Z'bookingservice/api/bookingservice/v1;v1b\x06proto3"

var (
	file_bookingservice_v1_booking_proto_rawDescOnce sync.Once
	file_bookingservice_v1_booking_proto_rawDescData []byte
)

func file_bookingservice_v1_booking_proto_rawDescGZIP() []byte {
	file_bookingservice_v1_booking_proto_rawDescOnce.Do(func() {
		file_bookingservice_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookingservice_v1_booking_proto_rawDesc), len(file_bookingservice_v1_booking_proto_rawDesc)))
	})
	return file_bookingservice_v1_booking_proto_rawDescData
}

var file_bookingservice_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_bookingservice_v1_booking_proto_goTypes = []any{
	(*Booking)(nil),               // 0: booking.v1.Booking
	(*CreateBookingRequest)(nil),  // 1: booking.v1.CreateBookingRequest
	(*CreateBookingReply)(nil),    // 2: booking.v1.CreateBookingReply
	(*GetBookingRequest)(nil),     // 3: booking.v1.GetBookingRequest
	(*ListBookingsRequest)(nil),   // 4: booking.v1.ListBookingsRequest
	(*ListBookingsReply)(nil),     // 5: booking.v1.ListBookingsReply
	(*CancelBookingRequest)(nil),  // 6: booking.v1.CancelBookingRequest
	(*ConfirmBookingRequest)(nil), // 7: booking.v1.ConfirmBookingRequest
	(*ConfirmBookingReply)(nil),   // 8: booking.v1.ConfirmBookingReply
	(*UpdateBookingRequest)(nil),  // 9: booking.v1.UpdateBookingRequest
	(*UpdateBookingReply)(nil),    // 10: booking.v1.UpdateBookingReply
	(*GetLockedSeatsRequest)(nil), // 11: booking.v1.GetLockedSeatsRequest
	(*GetLockedSeatsReply)(nil),   // 12: booking.v1.GetLockedSeatsReply
	(*LockSeatRequest)(nil),       // 13: booking.v1.LockSeatRequest
	(*LockSeatReply)(nil),         // 14: booking.v1.LockSeatReply
	(*UnlockSeatRequest)(nil),     // 15: booking.v1.UnlockSeatRequest
	(*UnlockSeatReply)(nil),       // 16: booking.v1.UnlockSeatReply
	(*GetBookedSeatsRequest)(nil), // 17: booking.v1.GetBookedSeatsRequest
	(*GetBookedSeatsReply)(nil),   // 18: booking.v1.GetBookedSeatsReply
	(*GetEventRequest)(nil),       // 19: booking.v1.GetEventRequest
	(*GetEventReply)(nil),         // 20: booking.v1.GetEventReply
}
var file_bookingservice_v1_booking_proto_depIdxs = []int32{
	0,  // 0: booking.v1.CreateBookingReply.booking:type_name -> booking.v1.Booking
	0,  // 1: booking.v1.ListBookingsReply.bookings:type_name -> booking.v1.Booking
	1,  // 2: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	3,  // 3: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	4,  // 4: booking.v1.BookingService.ListBookings:input_type -> booking.v1.ListBookingsRequest
	9,  // 5: booking.v1.BookingService.UpdateBooking:input_type -> booking.v1.UpdateBookingRequest
	6,  // 6: booking.v1.BookingService.CancelBooking:input_type -> booking.v1.CancelBookingRequest
	7,  // 7: booking.v1.BookingService.ConfirmBooking:input_type -> booking.v1.ConfirmBookingRequest
	17, // 8: booking.v1.BookingService.GetBookedSeats:input_type -> booking.v1.GetBookedSeatsRequest
	11, // 9: booking.v1.BookingService.GetLockedSeats:input_type -> booking.v1.GetLockedSeatsRequest
	13, // 10: booking.v1.BookingService.LockSeat:input_type -> booking.v1.LockSeatRequest
	15, // 11: booking.v1.BookingService.UnlockSeat:input_type -> booking.v1.UnlockSeatRequest
	19, // 12: booking.v1.BookingService.GetEvent:input_type -> booking.v1.GetEventRequest
	2,  // 13: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.CreateBookingReply
	2,  // 14: booking.v1.BookingService.GetBooking:output_type -> booking.v1.CreateBookingReply
	5,  // 15: booking.v1.BookingService.ListBookings:output_type -> booking.v1.ListBookingsReply
	10, // 16: booking.v1.BookingService.UpdateBooking:output_type -> booking.v1.UpdateBookingReply
	2,  // 17: booking.v1.BookingService.CancelBooking:output_type -> booking.v1.CreateBookingReply
	2,  // 18: booking.v1.BookingService.ConfirmBooking:output_type -> booking.v1.CreateBookingReply
	18, // 19: booking.v1.BookingService.GetBookedSeats:output_type -> booking.v1.GetBookedSeatsReply
	12, // 20: booking.v1.BookingService.GetLockedSeats:output_type -> booking.v1.GetLockedSeatsReply
	14, // 21: booking.v1.BookingService.LockSeat:output_type -> booking.v1.LockSeatReply
	16, // 22: booking.v1.BookingService.UnlockSeat:output_type -> booking.v1.UnlockSeatReply
	20, // 23: booking.v1.BookingService.GetEvent:output_type -> booking.v1.GetEventReply
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_bookingservice_v1_booking_proto_init() }
func file_bookingservice_v1_booking_proto_init() {
	if File_bookingservice_v1_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookingservice_v1_booking_proto_rawDesc), len(file_bookingservice_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookingservice_v1_booking_proto_goTypes,
		DependencyIndexes: file_bookingservice_v1_booking_proto_depIdxs,
		MessageInfos:      file_bookingservice_v1_booking_proto_msgTypes,
	}.Build()
	File_bookingservice_v1_booking_proto = out.File
	file_bookingservice_v1_booking_proto_goTypes = nil
	file_bookingservice_v1_booking_proto_depIdxs = nil
}
