// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"eventservice/internal/biz"
	"eventservice/internal/conf"
	"eventservice/internal/data"
	"eventservice/internal/server"
	"eventservice/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	showEventRepo := data.NewShowEventRepo(db)
	userServiceClient, cleanup2, err := data.ProvideUserClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	showEventUsecase := biz.NewShowEventUsecase(showEventRepo, userServiceClient, logger)
	showEventService := service.NewShowEventService(showEventUsecase, userServiceClient)
	grpcServer := server.NewGRPCServer(confServer, showEventService, logger)
	httpServer := server.NewHTTPServer(confServer, showEventService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
