// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"notificationservice/internal/biz"
	"notificationservice/internal/conf"
	"notificationservice/internal/data"
	"notificationservice/internal/server"
	"notificationservice/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, confEmail *conf.Email, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(db, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationRepo := data.NewNotificationRepo(dataData, logger)
	emailConfig := biz.ProvideEmailConfig(confEmail)
	notificationUsecase := biz.NewNotificationUsecase(notificationRepo, emailConfig)
	bookingServiceClient, cleanup3, err := data.ProvideBookingClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userServiceClient, cleanup4, err := data.ProvideUserClient()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationService := service.NewNotificationService(notificationUsecase, bookingServiceClient, userServiceClient, logger)
	grpcServer := server.NewGRPCServer(confServer, notificationService, logger)
	httpServer := server.NewHTTPServer(confServer, notificationService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
