// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: paymentservice/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request: only booking_id and payment_method
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint64                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_paymentservice_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentservice_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentservice_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetBookingId() uint64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

// Response: all details returned by service
type CreatePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint64                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BookingId     uint64                 `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                        // PENDING / PAID / FAILED
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // formatted timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReply) Reset() {
	*x = CreatePaymentReply{}
	mi := &file_paymentservice_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReply) ProtoMessage() {}

func (x *CreatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_paymentservice_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReply.ProtoReflect.Descriptor instead.
func (*CreatePaymentReply) Descriptor() ([]byte, []int) {
	return file_paymentservice_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentReply) GetPaymentId() uint64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CreatePaymentReply) GetBookingId() uint64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CreatePaymentReply) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentReply) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePaymentReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_paymentservice_v1_payment_proto protoreflect.FileDescriptor

const file_paymentservice_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fpaymentservice/v1/payment.proto\x12\x11paymentservice.v1\x1a\x1cgoogle/api/annotations.proto\"\\\n" +
	"\x14CreatePaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x04R\tbookingId\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\"\xb9\x01\n" +
	"\x12CreatePaymentReply\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x04R\tpaymentId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x04R\tbookingId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\x8a\x01\n" +
	"\x0ePaymentService\x12x\n" +
	"\rCreatePayment\x12'.paymentservice.v1.CreatePaymentRequest\x1a%.paymentservice.v1.CreatePaymentReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/paymentsBd\n" +
	" dev.kratos.api.paymentservice.v1B\x15PaymentserviceProtoV1P\x01Z'paymentservice/api/paymentservice/v1;v1b\x06proto3"

var (
	file_paymentservice_v1_payment_proto_rawDescOnce sync.Once
	file_paymentservice_v1_payment_proto_rawDescData []byte
)

func file_paymentservice_v1_payment_proto_rawDescGZIP() []byte {
	file_paymentservice_v1_payment_proto_rawDescOnce.Do(func() {
		file_paymentservice_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentservice_v1_payment_proto_rawDesc), len(file_paymentservice_v1_payment_proto_rawDesc)))
	})
	return file_paymentservice_v1_payment_proto_rawDescData
}

var file_paymentservice_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paymentservice_v1_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil), // 0: paymentservice.v1.CreatePaymentRequest
	(*CreatePaymentReply)(nil),   // 1: paymentservice.v1.CreatePaymentReply
}
var file_paymentservice_v1_payment_proto_depIdxs = []int32{
	0, // 0: paymentservice.v1.PaymentService.CreatePayment:input_type -> paymentservice.v1.CreatePaymentRequest
	1, // 1: paymentservice.v1.PaymentService.CreatePayment:output_type -> paymentservice.v1.CreatePaymentReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymentservice_v1_payment_proto_init() }
func file_paymentservice_v1_payment_proto_init() {
	if File_paymentservice_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentservice_v1_payment_proto_rawDesc), len(file_paymentservice_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentservice_v1_payment_proto_goTypes,
		DependencyIndexes: file_paymentservice_v1_payment_proto_depIdxs,
		MessageInfos:      file_paymentservice_v1_payment_proto_msgTypes,
	}.Build()
	File_paymentservice_v1_payment_proto = out.File
	file_paymentservice_v1_payment_proto_goTypes = nil
	file_paymentservice_v1_payment_proto_depIdxs = nil
}
