// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: eventservice/v1/event.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date           string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"` // ISO8601 string
	TotalSeats     int32                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,6,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	PricePerSeat   float32                `protobuf:"fixed32,7,opt,name=price_per_seat,json=pricePerSeat,proto3" json:"price_per_seat,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShowEvent) Reset() {
	*x = ShowEvent{}
	mi := &file_eventservice_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowEvent) ProtoMessage() {}

func (x *ShowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowEvent.ProtoReflect.Descriptor instead.
func (*ShowEvent) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ShowEvent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShowEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShowEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShowEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ShowEvent) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *ShowEvent) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *ShowEvent) GetPricePerSeat() float32 {
	if x != nil {
		return x.PricePerSeat
	}
	return 0
}

type CreateShowEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	PricePerSeat  float32                `protobuf:"fixed32,4,opt,name=price_per_seat,json=pricePerSeat,proto3" json:"price_per_seat,omitempty"`
	TotalSeats    int32                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShowEventRequest) Reset() {
	*x = CreateShowEventRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShowEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShowEventRequest) ProtoMessage() {}

func (x *CreateShowEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShowEventRequest.ProtoReflect.Descriptor instead.
func (*CreateShowEventRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShowEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateShowEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateShowEventRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateShowEventRequest) GetPricePerSeat() float32 {
	if x != nil {
		return x.PricePerSeat
	}
	return 0
}

func (x *CreateShowEventRequest) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

type ShowEventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowEvent     *ShowEvent             `protobuf:"bytes,1,opt,name=show_event,json=showEvent,proto3" json:"show_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowEventReply) Reset() {
	*x = ShowEventReply{}
	mi := &file_eventservice_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowEventReply) ProtoMessage() {}

func (x *ShowEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowEventReply.ProtoReflect.Descriptor instead.
func (*ShowEventReply) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *ShowEventReply) GetShowEvent() *ShowEvent {
	if x != nil {
		return x.ShowEvent
	}
	return nil
}

type GetShowEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowEventRequest) Reset() {
	*x = GetShowEventRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowEventRequest) ProtoMessage() {}

func (x *GetShowEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowEventRequest.ProtoReflect.Descriptor instead.
func (*GetShowEventRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetShowEventRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListShowEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowEventsRequest) Reset() {
	*x = ListShowEventsRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowEventsRequest) ProtoMessage() {}

func (x *ListShowEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowEventsRequest.ProtoReflect.Descriptor instead.
func (*ListShowEventsRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{4}
}

type ListShowEventsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowEvents    []*ShowEvent           `protobuf:"bytes,1,rep,name=show_events,json=showEvents,proto3" json:"show_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShowEventsReply) Reset() {
	*x = ListShowEventsReply{}
	mi := &file_eventservice_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShowEventsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShowEventsReply) ProtoMessage() {}

func (x *ListShowEventsReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShowEventsReply.ProtoReflect.Descriptor instead.
func (*ListShowEventsReply) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *ListShowEventsReply) GetShowEvents() []*ShowEvent {
	if x != nil {
		return x.ShowEvents
	}
	return nil
}

type UpdateShowEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date           string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"` // ISO8601 string
	TotalSeats     int32                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,6,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	PricePerSeat   float32                `protobuf:"fixed32,7,opt,name=price_per_seat,json=pricePerSeat,proto3" json:"price_per_seat,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShowEventRequest) Reset() {
	*x = UpdateShowEventRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShowEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShowEventRequest) ProtoMessage() {}

func (x *UpdateShowEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShowEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateShowEventRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateShowEventRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateShowEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateShowEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateShowEventRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateShowEventRequest) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *UpdateShowEventRequest) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *UpdateShowEventRequest) GetPricePerSeat() float32 {
	if x != nil {
		return x.PricePerSeat
	}
	return 0
}

type DeleteShowEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowEventRequest) Reset() {
	*x = DeleteShowEventRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowEventRequest) ProtoMessage() {}

func (x *DeleteShowEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteShowEventRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteShowEventRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteShowEventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShowEventReply) Reset() {
	*x = DeleteShowEventReply{}
	mi := &file_eventservice_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShowEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShowEventReply) ProtoMessage() {}

func (x *DeleteShowEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShowEventReply.ProtoReflect.Descriptor instead.
func (*DeleteShowEventReply) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteShowEventReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserRequest) Reset() {
	*x = ValidateUserRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserRequest) ProtoMessage() {}

func (x *ValidateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ValidateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserReply) Reset() {
	*x = ValidateUserReply{}
	mi := &file_eventservice_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserReply) ProtoMessage() {}

func (x *ValidateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserReply.ProtoReflect.Descriptor instead.
func (*ValidateUserReply) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateUserReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ValidateUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DecrementSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementSeatsRequest) Reset() {
	*x = DecrementSeatsRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementSeatsRequest) ProtoMessage() {}

func (x *DecrementSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementSeatsRequest.ProtoReflect.Descriptor instead.
func (*DecrementSeatsRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *DecrementSeatsRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *DecrementSeatsRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type DecrementSeatsReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,3,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecrementSeatsReply) Reset() {
	*x = DecrementSeatsReply{}
	mi := &file_eventservice_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementSeatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementSeatsReply) ProtoMessage() {}

func (x *DecrementSeatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementSeatsReply.ProtoReflect.Descriptor instead.
func (*DecrementSeatsReply) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *DecrementSeatsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecrementSeatsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DecrementSeatsReply) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

type IncrementSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,2,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementSeatsRequest) Reset() {
	*x = IncrementSeatsRequest{}
	mi := &file_eventservice_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementSeatsRequest) ProtoMessage() {}

func (x *IncrementSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementSeatsRequest.ProtoReflect.Descriptor instead.
func (*IncrementSeatsRequest) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *IncrementSeatsRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *IncrementSeatsRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type IncrementSeatsReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,2,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncrementSeatsReply) Reset() {
	*x = IncrementSeatsReply{}
	mi := &file_eventservice_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementSeatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementSeatsReply) ProtoMessage() {}

func (x *IncrementSeatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventservice_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementSeatsReply.ProtoReflect.Descriptor instead.
func (*IncrementSeatsReply) Descriptor() ([]byte, []int) {
	return file_eventservice_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *IncrementSeatsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IncrementSeatsReply) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

var File_eventservice_v1_event_proto protoreflect.FileDescriptor

const file_eventservice_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1beventservice/v1/event.proto\x12\bevent.v1\x1a\x1cgoogle/api/annotations.proto\"\xd7\x01\n" +
	"\tShowEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\x06 \x01(\x05R\x0eavailableSeats\x12$\n" +
	"\x0eprice_per_seat\x18\a \x01(\x02R\fpricePerSeat\"\xab\x01\n" +
	"\x16CreateShowEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12$\n" +
	"\x0eprice_per_seat\x18\x04 \x01(\x02R\fpricePerSeat\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x05R\n" +
	"totalSeats\"D\n" +
	"\x0eShowEventReply\x122\n" +
	"\n" +
	"show_event\x18\x01 \x01(\v2\x13.event.v1.ShowEventR\tshowEvent\"%\n" +
	"\x13GetShowEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x17\n" +
	"\x15ListShowEventsRequest\"K\n" +
	"\x13ListShowEventsReply\x124\n" +
	"\vshow_events\x18\x01 \x03(\v2\x13.event.v1.ShowEventR\n" +
	"showEvents\"\xe4\x01\n" +
	"\x16UpdateShowEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\x06 \x01(\x05R\x0eavailableSeats\x12$\n" +
	"\x0eprice_per_seat\x18\a \x01(\x02R\fpricePerSeat\"(\n" +
	"\x16DeleteShowEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"0\n" +
	"\x14DeleteShowEventReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x13ValidateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"C\n" +
	"\x11ValidateUserReply\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x15DecrementSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\"r\n" +
	"\x13DecrementSeatsReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0favailable_seats\x18\x03 \x01(\x05R\x0eavailableSeats\"M\n" +
	"\x15IncrementSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x19\n" +
	"\bseat_ids\x18\x02 \x03(\tR\aseatIds\"X\n" +
	"\x13IncrementSeatsReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0favailable_seats\x18\x02 \x01(\x05R\x0eavailableSeats2\xfa\x06\n" +
	"\fEventService\x12f\n" +
	"\x0fCreateShowEvent\x12 .event.v1.CreateShowEventRequest\x1a\x18.event.v1.ShowEventReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/show-events\x12b\n" +
	"\fGetShowEvent\x12\x1d.event.v1.GetShowEventRequest\x1a\x18.event.v1.ShowEventReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/show-events/{id}\x12f\n" +
	"\x0eListShowEvents\x12\x1f.event.v1.ListShowEventsRequest\x1a\x1d.event.v1.ListShowEventsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/show-events\x12k\n" +
	"\x0fUpdateShowEvent\x12 .event.v1.UpdateShowEventRequest\x1a\x18.event.v1.ShowEventReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/show-events/{id}\x12n\n" +
	"\x0fDeleteShowEvent\x12 .event.v1.DeleteShowEventRequest\x1a\x1e.event.v1.DeleteShowEventReply\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/show-events/{id}\x12g\n" +
	"\fValidateUser\x12\x1d.event.v1.ValidateUserRequest\x1a\x1b.event.v1.ValidateUserReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/validate-user/{id}\x12w\n" +
	"\x0eDecrementSeats\x12\x1f.event.v1.DecrementSeatsRequest\x1a\x1d.event.v1.DecrementSeatsReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/events/decrement-seats\x12w\n" +
	"\x0eIncrementSeats\x12\x1f.event.v1.IncrementSeatsRequest\x1a\x1d.event.v1.IncrementSeatsReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/events/Increment-seatsB%Z#eventservice/api/eventservice/v1;v1b\x06proto3"

var (
	file_eventservice_v1_event_proto_rawDescOnce sync.Once
	file_eventservice_v1_event_proto_rawDescData []byte
)

func file_eventservice_v1_event_proto_rawDescGZIP() []byte {
	file_eventservice_v1_event_proto_rawDescOnce.Do(func() {
		file_eventservice_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventservice_v1_event_proto_rawDesc), len(file_eventservice_v1_event_proto_rawDesc)))
	})
	return file_eventservice_v1_event_proto_rawDescData
}

var file_eventservice_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_eventservice_v1_event_proto_goTypes = []any{
	(*ShowEvent)(nil),              // 0: event.v1.ShowEvent
	(*CreateShowEventRequest)(nil), // 1: event.v1.CreateShowEventRequest
	(*ShowEventReply)(nil),         // 2: event.v1.ShowEventReply
	(*GetShowEventRequest)(nil),    // 3: event.v1.GetShowEventRequest
	(*ListShowEventsRequest)(nil),  // 4: event.v1.ListShowEventsRequest
	(*ListShowEventsReply)(nil),    // 5: event.v1.ListShowEventsReply
	(*UpdateShowEventRequest)(nil), // 6: event.v1.UpdateShowEventRequest
	(*DeleteShowEventRequest)(nil), // 7: event.v1.DeleteShowEventRequest
	(*DeleteShowEventReply)(nil),   // 8: event.v1.DeleteShowEventReply
	(*ValidateUserRequest)(nil),    // 9: event.v1.ValidateUserRequest
	(*ValidateUserReply)(nil),      // 10: event.v1.ValidateUserReply
	(*DecrementSeatsRequest)(nil),  // 11: event.v1.DecrementSeatsRequest
	(*DecrementSeatsReply)(nil),    // 12: event.v1.DecrementSeatsReply
	(*IncrementSeatsRequest)(nil),  // 13: event.v1.IncrementSeatsRequest
	(*IncrementSeatsReply)(nil),    // 14: event.v1.IncrementSeatsReply
}
var file_eventservice_v1_event_proto_depIdxs = []int32{
	0,  // 0: event.v1.ShowEventReply.show_event:type_name -> event.v1.ShowEvent
	0,  // 1: event.v1.ListShowEventsReply.show_events:type_name -> event.v1.ShowEvent
	1,  // 2: event.v1.EventService.CreateShowEvent:input_type -> event.v1.CreateShowEventRequest
	3,  // 3: event.v1.EventService.GetShowEvent:input_type -> event.v1.GetShowEventRequest
	4,  // 4: event.v1.EventService.ListShowEvents:input_type -> event.v1.ListShowEventsRequest
	6,  // 5: event.v1.EventService.UpdateShowEvent:input_type -> event.v1.UpdateShowEventRequest
	7,  // 6: event.v1.EventService.DeleteShowEvent:input_type -> event.v1.DeleteShowEventRequest
	9,  // 7: event.v1.EventService.ValidateUser:input_type -> event.v1.ValidateUserRequest
	11, // 8: event.v1.EventService.DecrementSeats:input_type -> event.v1.DecrementSeatsRequest
	13, // 9: event.v1.EventService.IncrementSeats:input_type -> event.v1.IncrementSeatsRequest
	2,  // 10: event.v1.EventService.CreateShowEvent:output_type -> event.v1.ShowEventReply
	2,  // 11: event.v1.EventService.GetShowEvent:output_type -> event.v1.ShowEventReply
	5,  // 12: event.v1.EventService.ListShowEvents:output_type -> event.v1.ListShowEventsReply
	2,  // 13: event.v1.EventService.UpdateShowEvent:output_type -> event.v1.ShowEventReply
	8,  // 14: event.v1.EventService.DeleteShowEvent:output_type -> event.v1.DeleteShowEventReply
	10, // 15: event.v1.EventService.ValidateUser:output_type -> event.v1.ValidateUserReply
	12, // 16: event.v1.EventService.DecrementSeats:output_type -> event.v1.DecrementSeatsReply
	14, // 17: event.v1.EventService.IncrementSeats:output_type -> event.v1.IncrementSeatsReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_eventservice_v1_event_proto_init() }
func file_eventservice_v1_event_proto_init() {
	if File_eventservice_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventservice_v1_event_proto_rawDesc), len(file_eventservice_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventservice_v1_event_proto_goTypes,
		DependencyIndexes: file_eventservice_v1_event_proto_depIdxs,
		MessageInfos:      file_eventservice_v1_event_proto_msgTypes,
	}.Build()
	File_eventservice_v1_event_proto = out.File
	file_eventservice_v1_event_proto_goTypes = nil
	file_eventservice_v1_event_proto_depIdxs = nil
}
