// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: eventservice/v1/event.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_CreateShowEvent_FullMethodName = "/event.v1.EventService/CreateShowEvent"
	EventService_GetShowEvent_FullMethodName    = "/event.v1.EventService/GetShowEvent"
	EventService_ListShowEvents_FullMethodName  = "/event.v1.EventService/ListShowEvents"
	EventService_UpdateShowEvent_FullMethodName = "/event.v1.EventService/UpdateShowEvent"
	EventService_DeleteShowEvent_FullMethodName = "/event.v1.EventService/DeleteShowEvent"
	EventService_ValidateUser_FullMethodName    = "/event.v1.EventService/ValidateUser"
	EventService_DecrementSeats_FullMethodName  = "/event.v1.EventService/DecrementSeats"
	EventService_IncrementSeats_FullMethodName  = "/event.v1.EventService/IncrementSeats"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	// ---------------- ShowEvent CRUD ----------------
	CreateShowEvent(ctx context.Context, in *CreateShowEventRequest, opts ...grpc.CallOption) (*ShowEventReply, error)
	GetShowEvent(ctx context.Context, in *GetShowEventRequest, opts ...grpc.CallOption) (*ShowEventReply, error)
	ListShowEvents(ctx context.Context, in *ListShowEventsRequest, opts ...grpc.CallOption) (*ListShowEventsReply, error)
	UpdateShowEvent(ctx context.Context, in *UpdateShowEventRequest, opts ...grpc.CallOption) (*ShowEventReply, error)
	DeleteShowEvent(ctx context.Context, in *DeleteShowEventRequest, opts ...grpc.CallOption) (*DeleteShowEventReply, error)
	ValidateUser(ctx context.Context, in *ValidateUserRequest, opts ...grpc.CallOption) (*ValidateUserReply, error)
	DecrementSeats(ctx context.Context, in *DecrementSeatsRequest, opts ...grpc.CallOption) (*DecrementSeatsReply, error)
	IncrementSeats(ctx context.Context, in *IncrementSeatsRequest, opts ...grpc.CallOption) (*IncrementSeatsReply, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateShowEvent(ctx context.Context, in *CreateShowEventRequest, opts ...grpc.CallOption) (*ShowEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowEventReply)
	err := c.cc.Invoke(ctx, EventService_CreateShowEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetShowEvent(ctx context.Context, in *GetShowEventRequest, opts ...grpc.CallOption) (*ShowEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowEventReply)
	err := c.cc.Invoke(ctx, EventService_GetShowEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListShowEvents(ctx context.Context, in *ListShowEventsRequest, opts ...grpc.CallOption) (*ListShowEventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShowEventsReply)
	err := c.cc.Invoke(ctx, EventService_ListShowEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateShowEvent(ctx context.Context, in *UpdateShowEventRequest, opts ...grpc.CallOption) (*ShowEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowEventReply)
	err := c.cc.Invoke(ctx, EventService_UpdateShowEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteShowEvent(ctx context.Context, in *DeleteShowEventRequest, opts ...grpc.CallOption) (*DeleteShowEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShowEventReply)
	err := c.cc.Invoke(ctx, EventService_DeleteShowEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ValidateUser(ctx context.Context, in *ValidateUserRequest, opts ...grpc.CallOption) (*ValidateUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateUserReply)
	err := c.cc.Invoke(ctx, EventService_ValidateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DecrementSeats(ctx context.Context, in *DecrementSeatsRequest, opts ...grpc.CallOption) (*DecrementSeatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementSeatsReply)
	err := c.cc.Invoke(ctx, EventService_DecrementSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) IncrementSeats(ctx context.Context, in *IncrementSeatsRequest, opts ...grpc.CallOption) (*IncrementSeatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementSeatsReply)
	err := c.cc.Invoke(ctx, EventService_IncrementSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	// ---------------- ShowEvent CRUD ----------------
	CreateShowEvent(context.Context, *CreateShowEventRequest) (*ShowEventReply, error)
	GetShowEvent(context.Context, *GetShowEventRequest) (*ShowEventReply, error)
	ListShowEvents(context.Context, *ListShowEventsRequest) (*ListShowEventsReply, error)
	UpdateShowEvent(context.Context, *UpdateShowEventRequest) (*ShowEventReply, error)
	DeleteShowEvent(context.Context, *DeleteShowEventRequest) (*DeleteShowEventReply, error)
	ValidateUser(context.Context, *ValidateUserRequest) (*ValidateUserReply, error)
	DecrementSeats(context.Context, *DecrementSeatsRequest) (*DecrementSeatsReply, error)
	IncrementSeats(context.Context, *IncrementSeatsRequest) (*IncrementSeatsReply, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) CreateShowEvent(context.Context, *CreateShowEventRequest) (*ShowEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShowEvent not implemented")
}
func (UnimplementedEventServiceServer) GetShowEvent(context.Context, *GetShowEventRequest) (*ShowEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShowEvent not implemented")
}
func (UnimplementedEventServiceServer) ListShowEvents(context.Context, *ListShowEventsRequest) (*ListShowEventsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShowEvents not implemented")
}
func (UnimplementedEventServiceServer) UpdateShowEvent(context.Context, *UpdateShowEventRequest) (*ShowEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShowEvent not implemented")
}
func (UnimplementedEventServiceServer) DeleteShowEvent(context.Context, *DeleteShowEventRequest) (*DeleteShowEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShowEvent not implemented")
}
func (UnimplementedEventServiceServer) ValidateUser(context.Context, *ValidateUserRequest) (*ValidateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateUser not implemented")
}
func (UnimplementedEventServiceServer) DecrementSeats(context.Context, *DecrementSeatsRequest) (*DecrementSeatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrementSeats not implemented")
}
func (UnimplementedEventServiceServer) IncrementSeats(context.Context, *IncrementSeatsRequest) (*IncrementSeatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementSeats not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateShowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShowEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateShowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateShowEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateShowEvent(ctx, req.(*CreateShowEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetShowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShowEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetShowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetShowEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetShowEvent(ctx, req.(*GetShowEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListShowEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShowEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListShowEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListShowEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListShowEvents(ctx, req.(*ListShowEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateShowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShowEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateShowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateShowEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateShowEvent(ctx, req.(*UpdateShowEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteShowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShowEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteShowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteShowEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteShowEvent(ctx, req.(*DeleteShowEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ValidateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ValidateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ValidateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ValidateUser(ctx, req.(*ValidateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DecrementSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DecrementSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DecrementSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DecrementSeats(ctx, req.(*DecrementSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_IncrementSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).IncrementSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_IncrementSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).IncrementSeats(ctx, req.(*IncrementSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShowEvent",
			Handler:    _EventService_CreateShowEvent_Handler,
		},
		{
			MethodName: "GetShowEvent",
			Handler:    _EventService_GetShowEvent_Handler,
		},
		{
			MethodName: "ListShowEvents",
			Handler:    _EventService_ListShowEvents_Handler,
		},
		{
			MethodName: "UpdateShowEvent",
			Handler:    _EventService_UpdateShowEvent_Handler,
		},
		{
			MethodName: "DeleteShowEvent",
			Handler:    _EventService_DeleteShowEvent_Handler,
		},
		{
			MethodName: "ValidateUser",
			Handler:    _EventService_ValidateUser_Handler,
		},
		{
			MethodName: "DecrementSeats",
			Handler:    _EventService_DecrementSeats_Handler,
		},
		{
			MethodName: "IncrementSeats",
			Handler:    _EventService_IncrementSeats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventservice/v1/event.proto",
}
