// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.32.0
// source: eventservice/v1/event.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEventServiceCreateShowEvent = "/event.v1.EventService/CreateShowEvent"
const OperationEventServiceDecrementSeats = "/event.v1.EventService/DecrementSeats"
const OperationEventServiceDeleteShowEvent = "/event.v1.EventService/DeleteShowEvent"
const OperationEventServiceGetShowEvent = "/event.v1.EventService/GetShowEvent"
const OperationEventServiceIncrementSeats = "/event.v1.EventService/IncrementSeats"
const OperationEventServiceListShowEvents = "/event.v1.EventService/ListShowEvents"
const OperationEventServiceUpdateShowEvent = "/event.v1.EventService/UpdateShowEvent"
const OperationEventServiceValidateUser = "/event.v1.EventService/ValidateUser"

type EventServiceHTTPServer interface {
	// CreateShowEvent ---------------- ShowEvent CRUD ----------------
	CreateShowEvent(context.Context, *CreateShowEventRequest) (*ShowEventReply, error)
	DecrementSeats(context.Context, *DecrementSeatsRequest) (*DecrementSeatsReply, error)
	DeleteShowEvent(context.Context, *DeleteShowEventRequest) (*DeleteShowEventReply, error)
	GetShowEvent(context.Context, *GetShowEventRequest) (*ShowEventReply, error)
	IncrementSeats(context.Context, *IncrementSeatsRequest) (*IncrementSeatsReply, error)
	ListShowEvents(context.Context, *ListShowEventsRequest) (*ListShowEventsReply, error)
	UpdateShowEvent(context.Context, *UpdateShowEventRequest) (*ShowEventReply, error)
	ValidateUser(context.Context, *ValidateUserRequest) (*ValidateUserReply, error)
}

func RegisterEventServiceHTTPServer(s *http.Server, srv EventServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/show-events", _EventService_CreateShowEvent0_HTTP_Handler(srv))
	r.GET("/show-events/{id}", _EventService_GetShowEvent0_HTTP_Handler(srv))
	r.GET("/show-events", _EventService_ListShowEvents0_HTTP_Handler(srv))
	r.PUT("/show-events/{id}", _EventService_UpdateShowEvent0_HTTP_Handler(srv))
	r.DELETE("/show-events/{id}", _EventService_DeleteShowEvent0_HTTP_Handler(srv))
	r.GET("/validate-user/{id}", _EventService_ValidateUser0_HTTP_Handler(srv))
	r.POST("/v1/events/decrement-seats", _EventService_DecrementSeats0_HTTP_Handler(srv))
	r.POST("/v1/events/Increment-seats", _EventService_IncrementSeats0_HTTP_Handler(srv))
}

func _EventService_CreateShowEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShowEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceCreateShowEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShowEvent(ctx, req.(*CreateShowEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowEventReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_GetShowEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetShowEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceGetShowEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShowEvent(ctx, req.(*GetShowEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowEventReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_ListShowEvents0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShowEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceListShowEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShowEvents(ctx, req.(*ListShowEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShowEventsReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_UpdateShowEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateShowEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceUpdateShowEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateShowEvent(ctx, req.(*UpdateShowEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowEventReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_DeleteShowEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteShowEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceDeleteShowEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteShowEvent(ctx, req.(*DeleteShowEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteShowEventReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_ValidateUser0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidateUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceValidateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ValidateUser(ctx, req.(*ValidateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidateUserReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_DecrementSeats0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DecrementSeatsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceDecrementSeats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DecrementSeats(ctx, req.(*DecrementSeatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DecrementSeatsReply)
		return ctx.Result(200, reply)
	}
}

func _EventService_IncrementSeats0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IncrementSeatsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceIncrementSeats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IncrementSeats(ctx, req.(*IncrementSeatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IncrementSeatsReply)
		return ctx.Result(200, reply)
	}
}

type EventServiceHTTPClient interface {
	// CreateShowEvent ---------------- ShowEvent CRUD ----------------
	CreateShowEvent(ctx context.Context, req *CreateShowEventRequest, opts ...http.CallOption) (rsp *ShowEventReply, err error)
	DecrementSeats(ctx context.Context, req *DecrementSeatsRequest, opts ...http.CallOption) (rsp *DecrementSeatsReply, err error)
	DeleteShowEvent(ctx context.Context, req *DeleteShowEventRequest, opts ...http.CallOption) (rsp *DeleteShowEventReply, err error)
	GetShowEvent(ctx context.Context, req *GetShowEventRequest, opts ...http.CallOption) (rsp *ShowEventReply, err error)
	IncrementSeats(ctx context.Context, req *IncrementSeatsRequest, opts ...http.CallOption) (rsp *IncrementSeatsReply, err error)
	ListShowEvents(ctx context.Context, req *ListShowEventsRequest, opts ...http.CallOption) (rsp *ListShowEventsReply, err error)
	UpdateShowEvent(ctx context.Context, req *UpdateShowEventRequest, opts ...http.CallOption) (rsp *ShowEventReply, err error)
	ValidateUser(ctx context.Context, req *ValidateUserRequest, opts ...http.CallOption) (rsp *ValidateUserReply, err error)
}

type EventServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEventServiceHTTPClient(client *http.Client) EventServiceHTTPClient {
	return &EventServiceHTTPClientImpl{client}
}

// CreateShowEvent ---------------- ShowEvent CRUD ----------------
func (c *EventServiceHTTPClientImpl) CreateShowEvent(ctx context.Context, in *CreateShowEventRequest, opts ...http.CallOption) (*ShowEventReply, error) {
	var out ShowEventReply
	pattern := "/show-events"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceCreateShowEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) DecrementSeats(ctx context.Context, in *DecrementSeatsRequest, opts ...http.CallOption) (*DecrementSeatsReply, error) {
	var out DecrementSeatsReply
	pattern := "/v1/events/decrement-seats"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceDecrementSeats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) DeleteShowEvent(ctx context.Context, in *DeleteShowEventRequest, opts ...http.CallOption) (*DeleteShowEventReply, error) {
	var out DeleteShowEventReply
	pattern := "/show-events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceDeleteShowEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) GetShowEvent(ctx context.Context, in *GetShowEventRequest, opts ...http.CallOption) (*ShowEventReply, error) {
	var out ShowEventReply
	pattern := "/show-events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceGetShowEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) IncrementSeats(ctx context.Context, in *IncrementSeatsRequest, opts ...http.CallOption) (*IncrementSeatsReply, error) {
	var out IncrementSeatsReply
	pattern := "/v1/events/Increment-seats"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceIncrementSeats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) ListShowEvents(ctx context.Context, in *ListShowEventsRequest, opts ...http.CallOption) (*ListShowEventsReply, error) {
	var out ListShowEventsReply
	pattern := "/show-events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceListShowEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) UpdateShowEvent(ctx context.Context, in *UpdateShowEventRequest, opts ...http.CallOption) (*ShowEventReply, error) {
	var out ShowEventReply
	pattern := "/show-events/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceUpdateShowEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) ValidateUser(ctx context.Context, in *ValidateUserRequest, opts ...http.CallOption) (*ValidateUserReply, error) {
	var out ValidateUserReply
	pattern := "/validate-user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceValidateUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
