// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.32.0
// source: notificationservice/v1/notification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotificationServiceSendBookingNotification = "/notificationservice.v1.NotificationService/SendBookingNotification"

type NotificationServiceHTTPServer interface {
	SendBookingNotification(context.Context, *SendBookingNotificationRequest) (*SendBookingNotificationReply, error)
}

func RegisterNotificationServiceHTTPServer(s *http.Server, srv NotificationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/notification/send", _NotificationService_SendBookingNotification0_HTTP_Handler(srv))
}

func _NotificationService_SendBookingNotification0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendBookingNotificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceSendBookingNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendBookingNotification(ctx, req.(*SendBookingNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendBookingNotificationReply)
		return ctx.Result(200, reply)
	}
}

type NotificationServiceHTTPClient interface {
	SendBookingNotification(ctx context.Context, req *SendBookingNotificationRequest, opts ...http.CallOption) (rsp *SendBookingNotificationReply, err error)
}

type NotificationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationServiceHTTPClient(client *http.Client) NotificationServiceHTTPClient {
	return &NotificationServiceHTTPClientImpl{client}
}

func (c *NotificationServiceHTTPClientImpl) SendBookingNotification(ctx context.Context, in *SendBookingNotificationRequest, opts ...http.CallOption) (*SendBookingNotificationReply, error) {
	var out SendBookingNotificationReply
	pattern := "/v1/notification/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotificationServiceSendBookingNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
