// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: notificationservice/v1/notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for sending booking notification
type SendBookingNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     uint64                 `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"` // booking to notify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBookingNotificationRequest) Reset() {
	*x = SendBookingNotificationRequest{}
	mi := &file_notificationservice_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingNotificationRequest) ProtoMessage() {}

func (x *SendBookingNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationservice_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendBookingNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notificationservice_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendBookingNotificationRequest) GetBookingId() uint64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

// Reply for notification
type SendBookingNotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBookingNotificationReply) Reset() {
	*x = SendBookingNotificationReply{}
	mi := &file_notificationservice_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingNotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingNotificationReply) ProtoMessage() {}

func (x *SendBookingNotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_notificationservice_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingNotificationReply.ProtoReflect.Descriptor instead.
func (*SendBookingNotificationReply) Descriptor() ([]byte, []int) {
	return file_notificationservice_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendBookingNotificationReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendBookingNotificationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notificationservice_v1_notification_proto protoreflect.FileDescriptor

const file_notificationservice_v1_notification_proto_rawDesc = "" +
	"\n" +
	")notificationservice/v1/notification.proto\x12\x16notificationservice.v1\"?\n" +
	"\x1eSendBookingNotificationRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x04R\tbookingId\"R\n" +
	"\x1cSendBookingNotificationReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9f\x01\n" +
	"\x13NotificationService\x12\x87\x01\n" +
	"\x17SendBookingNotification\x126.notificationservice.v1.SendBookingNotificationRequest\x1a4.notificationservice.v1.SendBookingNotificationReplyB3Z1notificationservice/api/notificationservice/v1;v1b\x06proto3"

var (
	file_notificationservice_v1_notification_proto_rawDescOnce sync.Once
	file_notificationservice_v1_notification_proto_rawDescData []byte
)

func file_notificationservice_v1_notification_proto_rawDescGZIP() []byte {
	file_notificationservice_v1_notification_proto_rawDescOnce.Do(func() {
		file_notificationservice_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificationservice_v1_notification_proto_rawDesc), len(file_notificationservice_v1_notification_proto_rawDesc)))
	})
	return file_notificationservice_v1_notification_proto_rawDescData
}

var file_notificationservice_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notificationservice_v1_notification_proto_goTypes = []any{
	(*SendBookingNotificationRequest)(nil), // 0: notificationservice.v1.SendBookingNotificationRequest
	(*SendBookingNotificationReply)(nil),   // 1: notificationservice.v1.SendBookingNotificationReply
}
var file_notificationservice_v1_notification_proto_depIdxs = []int32{
	0, // 0: notificationservice.v1.NotificationService.SendBookingNotification:input_type -> notificationservice.v1.SendBookingNotificationRequest
	1, // 1: notificationservice.v1.NotificationService.SendBookingNotification:output_type -> notificationservice.v1.SendBookingNotificationReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificationservice_v1_notification_proto_init() }
func file_notificationservice_v1_notification_proto_init() {
	if File_notificationservice_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificationservice_v1_notification_proto_rawDesc), len(file_notificationservice_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificationservice_v1_notification_proto_goTypes,
		DependencyIndexes: file_notificationservice_v1_notification_proto_depIdxs,
		MessageInfos:      file_notificationservice_v1_notification_proto_msgTypes,
	}.Build()
	File_notificationservice_v1_notification_proto = out.File
	file_notificationservice_v1_notification_proto_goTypes = nil
	file_notificationservice_v1_notification_proto_depIdxs = nil
}
