// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"paymentservice/internal/biz"
	"paymentservice/internal/conf"
	"paymentservice/internal/data"
	"paymentservice/internal/server"
	"paymentservice/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp initializes PaymentService app.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	string2 := data.ProvideDSN(confData)
	db, cleanup, err := data.NewDB(string2)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(db)
	bookingServiceClient, cleanup2, err := data.ProvideBookingClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bookingClient := data.NewBookingClient(bookingServiceClient)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, bookingClient)
	paymentService := service.NewPaymentService(paymentUsecase)
	grpcServer := server.NewGRPCServer(confServer, paymentService, logger)
	httpServer := server.NewHTTPServer(confServer, paymentService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
