// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bookingservice/internal/biz"
	"bookingservice/internal/conf"
	"bookingservice/internal/data"
	"bookingservice/internal/server"
	"bookingservice/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := data.NewRedis(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bookingRepo := data.NewBookingRepo(db, client)
	eventServiceClient, cleanup3, err := data.ProvideEventClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bookingUsecase := biz.NewBookingUsecase(bookingRepo, eventServiceClient, logger)
	notificationServiceClient, cleanup4, err := data.ProvideNotificationClient()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	bookingService := service.NewBookingService(bookingUsecase, notificationServiceClient, eventServiceClient, logger)
	grpcServer := server.NewGRPCServer(confServer, bookingService, logger)
	httpServer := server.NewHTTPServer(confServer, bookingService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
